### ISSUE TITLE
misp-server can not be pulled

### ISSUE THREAD

**Issue by dr-holger** [DCSO/MISP-dockerized#2]
Hi,
misp-server image is not on dockerhub, at least not successfully build. Couldnt pull it therefor.
misp-robot and misp-proxy tagged with 2.4.88-beta.1 (in docker-compose.yml tag 2.4.88 is used)
Thanks
Holger

**Comment by 8ear** [comment]
Hi,
sorry for the issue. I will fix the issue as soon as possible.
Thanks for your feedback.

MH

**Comment by Mezzonian** [comment]
We have just released beta version 2, which should fix this problem. If the problem still occurs, please do not hesitate to open a new ticket.
