### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by stricaud** [DCSO/MISP-dockerized#66]
After pulling the last commit, I run docker-compose in current/

When I connect on the container IP, I have the following error:
```
502 Bad Gateway
nginx
```

And on the server side, I see those logs:
```
misp-proxy      | 2019/04/23 17:35:36 [error] 22#22: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.47.1, server: 9e1660a1b119, request: "GET / HTTP/2.0", upstream: "https://192.168.47.6:443/", host: "192.168.47.4"
misp-proxy      | 192.168.47.4 - 192.168.47.1 - - [23/Apr/2019:17:35:36 +0000] "GET / HTTP/2.0" 502 166 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "-"
```

**Comment by 8ear** [comment]
Normally you should not mix docker-compose and make commands.
Please can you try to go to the current folder and then `make deploy`?

**Comment by 8ear** [comment]
But please wait first that your issue #67 is solved.
Thx.

**Comment by stricaud** [comment]
ok perfect, I will wait and do the testing again.

**Comment by 8ear** [comment]
Can you do make deploy once again to test this?

**Comment by stricaud** [comment]
This is working. Thanks

**Comment by stricaud** [comment]
I re-open, I cleaned everything with make delete and run again, using make deploy inside current and I get the same error message. The server side logs I get are:
2019/04/30 08:13:42 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.32.5, server: 669e6910d657, request: "GET / HTTP/2.0", upstream: "https://192.168.47.6:443/", host: "misp.mysite.com"
misp.mysite.com - 172.16.32.5 - - [30/Apr/2019:08:13:42 +0000] "GET / HTTP/2.0" 502 150 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" "-"

**Comment by stricaud** [comment]
hum, it works again and I did not touch anything, just time... 

there is something here, I am not sure where to start debugging

**Comment by stricaud** [comment]
I am closing this and will re-open if I find this again. Thanks!
