### ISSUE TITLE
External DB Parameter ignored

### ISSUE THREAD

**Issue by iwm911** [DCSO/MISP-dockerized#74]
Hi,

When deploying with external DB it looks like the MYSQL_HOST parameter is not passed to the docker-compose.override.yml. this makes the entrypoint script to use the default value of localhost and ignore the external SQL server address and port
https://github.com/DCSO/MISP-dockerized/blob/9f6ea3a9c17e79ef8a823f152915658bc2ef7179/1.1.1/scripts/build_config.sh#L567

**Comment by iwm911** [comment]
Pull request to fix this issue (tested) https://github.com/DCSO/MISP-dockerized/pull/76

**Comment by 8ear** [comment]
Hi,
Thanks to your pull request. Yes it is right that current we do not support any external database. This will be changed with the next version 1.2.0.

I hope you won't be mad if we don't take over your pull request for 1.1.1 but add it to the new version 1.2.0.

**Comment by ghost** [comment]
Oh thank god, and dammit! I just spent two days trying to figure out why my MISP-dockerized deployment wasn't using the external database that I set up. Thank you for letting me know that I'm not crazy, and I look forward to 1.2.0 :-D

**Comment by 8ear** [comment]
#70
