### ISSUE TITLE
Updating MISP to latest version

### ISSUE THREAD

**Issue by stricaud** [DCSO/MISP-dockerized#75]
Whenever I go to this URL, in order to update my actual MISP instance to the latest version (which fixes some security issues):
https://misp-instance/servers/serverSettings/diagnostics
I see the following:
```
Currently installed version… v2.4.103 (aa2218846cab471cf5a0ae22afd79e231a74f3ca)
Latest available version… v2.4.107 ()
Status… Outdated version
Current branch… You are not on a branch, Update MISP will fail 
```
As I am not sure of the best way to do this, I also updated using the branch v1.2.0, and the returned version is still 2.4.103

I would assume this is a bug, or if I need to use the makefile in current, this is good, as long as I understand the best way to update.

Thank you!

**Comment by 8ear** [comment]
Hi 
Current the latest versions are not available. 
I can create all new versions as developer versions for you at the next week. 
These are not supported. Therefore they will not get any productive tags.

You can enable them by setting the following parameters in the config/config.env file:
`MISP_CONTAINER_TAG=2.4.107-debian-dev`

I will inform you about the progress.

**Comment by stricaud** [comment]
this is awesome, thanks
