### ISSUE TITLE
Existing database causes fail during server startup

### ISSUE THREAD

**Issue by melboyce** [DCSO/MISP-dockerized#79]
Due to the method of checking here: https://github.com/DCSO/MISP-dockerized-server/blob/master/2.4.103-debian/files/entrypoint_apache.sh#L361

an existing database will cause the server to fail to become healthy (table already exists or primary key already exists).

Perhaps we've missed an option/flag/config-item that will propagate down to the containers so that an existing database doesn't get reinitialized?

**Comment by 8ear** [comment]
I added also an pull request at MISP project https://github.com/MISP/MISP/pull/4939

**Comment by 8ear** [comment]
The pull request is fixed from MISP and it will be fixed at the new release 1.2.0 with MISP server 2.4.113.
