### ISSUE TITLE
Installation of MISP dockerized fails

### ISSUE THREAD

**Issue by begunrom** [DCSO/MISP-dockerized#82]
I tried to install MISP-dockerized 1.2.0 on a freshly installed Ubuntu 18.04 LTS. Installation is aborted as Pulling misp-db & misp-monitoring ends with error. (Version 1.1.1 is working)

How can I find out what is causing this error?

docker --version --> Docker version 19.03.2, build 6a30dfc
Docker was installed manually, not using snap

>  cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

> [build_config.sh] Check MISP server version ...
[build_config.sh] Do you want to enable nightly unsupported MISP server container? [ Default: no ]: no
[build_config.sh] Write configuration in /home/misp/MISP-dockerized/current/docker-compose.override.yml ... done
[build_config.sh] Write configuration in /home/misp/MISP-dockerized/config/config.env... done
[build_config.sh] To change the configuration, delete the corresponding line in:
[build_config.sh] /home/misp/MISP-dockerized/config/config.env
 ###########    Pull Environment        ###########
Unable to find image 'dcso/misp-dockerized-robot:2' locally
2: Pulling from dcso/misp-dockerized-robot
b8f262c62ec6: Pull complete
33654845d01f: Pull complete
dcbd0b415c1d: Pull complete
ba2f1435f414: Pull complete
dd9577a3d8a2: Pull complete
99cd884a2a6e: Pull complete
91118d140d71: Pull complete
c55ac37ac230: Pull complete
f834aa14ad99: Pull complete
71cab8789534: Pull complete
Digest: sha256:af8a58c4516a96c9a17c8e49471bc7add5cce7e8d7525f672a3338cac66dc2a0
Status: Downloaded newer image for dcso/misp-dockerized-robot:2
WARNING: The HTTP_PROXY variable is not set. Defaulting to a blank string.
WARNING: The HTTPS_PROXY variable is not set. Defaulting to a blank string.
WARNING: The NO_PROXY variable is not set. Defaulting to a blank string.
Pulling misp-monitoring ... error
Pulling misp-redis      ... done
Pulling misp-server     ... done
Pulling misp-modules    ... done
Pulling misp-proxy      ... done
Pulling misp-db         ... error
Pulling misp-robot      ... done
ERROR: for misp-monitoring  manifest for dcso/misp-dockerized-monitoring:latest not found: manifest unknown: manifest unknown
ERROR: for misp-db  manifest for dcso/misp-dockerized-db:10.4.5-bionic not found: manifest unknown: manifest unknown
ERROR: manifest for dcso/misp-dockerized-monitoring:latest not found: manifest unknown: manifest unknown
manifest for dcso/misp-dockerized-db:10.4.5-bionic not found: manifest unknown: manifest unknown
Makefile:45: recipe for target 'pull' failed
make[1]: *** [pull] Error 1
make[1]: Leaving directory '/home/misp/MISP-dockerized/1.2.0'
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by begunrom** [comment]
I enabled debugging on docker and below is what is in /var/log/syslog

What draws my attention is "Trying to pull dcso/misp-dockerized-db from https://registry-1.docker.io v2". 
There is a space between io and v2, while I would expect to see a "/" there. 
For now, I cannot find out if this just is a loggin issue or if this is indeed a problem with the script.

> Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.688374459Z" level=debug msg="Trying to pull dcso/misp-dockerized-monitoring from https://registry-1.docker.io v2"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.691731858Z" level=debug msg="Calling POST /v1.25/images/create?tag=2&fromImage=dcso%2Fmisp-dockerized-proxy"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.692048322Z" level=debug msg="Trying to pull dcso/misp-dockerized-proxy from https://registry-1.docker.io v2"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.694150192Z" level=debug msg="Calling POST /v1.25/images/create?tag=5-alpine3.9&fromImage=dcso%2Fmisp-dockerized-redis"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.694449099Z" level=debug msg="Trying to pull dcso/misp-dockerized-redis from https://registry-1.docker.io v2"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.696883792Z" level=debug msg="Calling POST /v1.25/images/create?tag=2.4.113-debian&fromImage=dcso%2Fmisp-dockerized-server"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.697172683Z" level=debug msg="Trying to pull dcso/misp-dockerized-server from https://registry-1.docker.io v2"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.699252004Z" level=debug msg="Calling POST /v1.25/images/create?tag=latest&fromImage=dcso%2Fmisp-dockerized-misp-modules"
Oct  3 16:29:10 test dockerd[3339]: time="2019-10-03T16:29:10.699587371Z" level=debug msg="Trying to pull dcso/misp-dockerized-misp-modules from https://registry-1.docker.io v2"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.171325386Z" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.176786998Z" level=debug msg="Calling POST /v1.25/images/create?tag=2&fromImage=dcso%2Fmisp-dockerized-robot"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.177127448Z" level=debug msg="Trying to pull dcso/misp-dockerized-robot from https://registry-1.docker.io v2"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.177918199Z" level=debug msg="Pulling ref from V2 registry: dcso/misp-dockerized-redis:5-alpine3.9"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.182606471Z" level=debug msg="Calling POST /v1.25/images/create?tag=10.4.5-bionic&fromImage=dcso%2Fmisp-dockerized-db"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.183166306Z" level=debug msg="Trying to pull dcso/misp-dockerized-db from https://registry-1.docker.io v2"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.190707972Z" level=debug msg="Pulling ref from V2 registry: dcso/misp-dockerized-proxy:2"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.193845986Z" level=debug msg="Pulling ref from V2 registry: dcso/misp-dockerized-server:2.4.113-debian"
Oct  3 16:29:17 test dockerd[3339]: time="2019-10-03T16:29:17.222708143Z" level=debug msg="Pulling ref from V2 registry: dcso/misp-dockerized-misp-modules:latest"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.580167806Z" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.622205396Z" level=debug msg="Pulling ref from V2 registry: dcso/misp-dockerized-robot:2"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.736587051Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/exit
Oct  3 16:29:18 test containerd[899]: time="2019-10-03T16:29:18.847024295Z" level=info msg="shim reaped" id=c62e186d59e4c12fb6428d79cdfde7bc77686a32bc2f7e9e4d8f41de69c29b42
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.857652915Z" level=debug msg=event module=libcontainerd namespace=moby topic=/tasks/delete
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.857677252Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.857784403Z" level=debug msg="attach: stdout: end"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.857808485Z" level=debug msg="attach: stdin: end"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.857815643Z" level=debug msg="attach: stderr: end"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.857834146Z" level=debug msg="attach done"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.861415601Z" level=debug msg="Closing buffered stdin pipe"
Oct  3 16:29:18 test dockerd[3339]: time="2019-10-03T16:29:18.873324205Z" level=warning msg="c62e186d59e4c12fb6428d79cdfde7bc77686a32bc2f7e9e4d8f41de69c29b42 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/c62e186d59e4c12fb6428d79cdfde7bc77686a32bc2f7e9e4d8f41de69c29b42/mounts/shm, flags: 0x2: no such file or directory"

**Comment by begunrom** [comment]
If I do a manual docker pull then the pull is successful, but the result is not stored on the same location as the "make install" command expects it. 

 What is going on?????????????

>  docker pull -a dcso/misp-dockerized-db
10.4.4-bionic-dev: Pulling from dcso/misp-dockerized-db
52e821cf85ae: Pull complete
4e4efc4c8e95: Pull complete
3c829501b976: Pull complete
8efcd2b4595b: Pull complete
9e9eb99c9050: Pull complete
7f49fa8dcb5e: Pull complete
06b91b425e81: Pull complete
309d785d303f: Pull complete
48e5d9d209e5: Pull complete
59156a9f2feb: Pull complete
f9fd24faddde: Downloading [===========================================>       ]  74.07MB/85.2MB
91f93789db6a: Download complete
0ea68955b12c: Download complete

**Comment by 8ear** [comment]
What is your result of: docker images

**Comment by begunrom** [comment]
docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
dcso/misp-dockerized-misp-modules   latest              fa75db9326a9        12 days ago         1.69GB
dcso/misp-dockerized-redis          5-alpine3.9         6f3559d51970        12 days ago         50.9MB
dcso/misp-dockerized-proxy          2                   caddd61a4115        2 weeks ago         24.3MB
dcso/misp-dockerized-server         2.4.113-debian      abd2dee0865c        2 weeks ago         1.82GB
dcso/misp-dockerized-robot          2                   2dda6dcdeafb        2 weeks ago         1.1GB
hello-world                         latest              fce289e99eb9        9 months ago        1.84kB

**Comment by begunrom** [comment]
Digest: sha256:af8a58c4516a96c9a17c8e49471bc7add5cce7e8d7525f672a3338cac66dc2a0
Status: Downloaded newer image for dcso/misp-dockerized-robot:2
WARNING: The HTTP_PROXY variable is not set. Defaulting to a blank string.
WARNING: The HTTPS_PROXY variable is not set. Defaulting to a blank string.
WARNING: The NO_PROXY variable is not set. Defaulting to a blank string.
Pulling misp-proxy      ... done
Pulling misp-db         ... error
Pulling misp-monitoring ... error
Pulling misp-redis      ... done
Pulling misp-robot      ... done
Pulling misp-modules    ... done
Pulling misp-server     ... done

ERROR: for misp-monitoring  manifest for dcso/misp-dockerized-monitoring:latest not found: manifest unknown: manifest unknown

ERROR: for misp-db  manifest for dcso/misp-dockerized-db:10.4.5-bionic not found: manifest unknown: manifest unknown
ERROR: manifest for dcso/misp-dockerized-monitoring:latest not found: manifest unknown: manifest unknown
manifest for dcso/misp-dockerized-db:10.4.5-bionic not found: manifest unknown: manifest unknown
Makefile:45: recipe for target 'pull' failed
make[1]: *** [pull] Error 1
make[1]: Leaving directory '/home/misp/MISP-dockerized/1.2.0'
Makefile:18: recipe for target 'install' failed
make: *** [install] Error 2
misp@test0:~/MISP-dockerized$ docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
dcso/misp-dockerized-misp-modules   latest              fa75db9326a9        12 days ago         1.69GB
dcso/misp-dockerized-redis          5-alpine3.9         6f3559d51970        12 days ago         50.9MB
dcso/misp-dockerized-proxy          2                   caddd61a4115        2 weeks ago         24.3MB
dcso/misp-dockerized-server         2.4.113-debian      abd2dee0865c        2 weeks ago         1.82GB
dcso/misp-dockerized-robot          2                   2dda6dcdeafb        2 weeks ago         1.1GB
hello-world                         latest              fce289e99eb9        9 months ago        1.84kB
misp@test0:~/MISP-dockerized$ docker pull -a dcso/misp-dockerized-db
10.4.4-bionic-dev: Pulling from dcso/misp-dockerized-db
52e821cf85ae: Pull complete
4e4efc4c8e95: Pull complete
3c829501b976: Pull complete
8efcd2b4595b: Pull complete
9e9eb99c9050: Pull complete
7f49fa8dcb5e: Pull complete
06b91b425e81: Pull complete
309d785d303f: Pull complete
48e5d9d209e5: Pull complete
59156a9f2feb: Pull complete
f9fd24faddde: Pull complete
91f93789db6a: Pull complete
0ea68955b12c: Pull complete
Digest: sha256:c4d00d0411fba211b5c1e88b249ac9c7555988f69095e5cd79761202e84168a1
manifest for dcso/misp-dockerized-db not found: manifest unknown: manifest unknown
misp@test0:~/MISP-dockerized$ docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
dcso/misp-dockerized-misp-modules   latest              fa75db9326a9        12 days ago         1.69GB
dcso/misp-dockerized-redis          5-alpine3.9         6f3559d51970        12 days ago         50.9MB
dcso/misp-dockerized-proxy          2                   caddd61a4115        2 weeks ago         24.3MB
dcso/misp-dockerized-server         2.4.113-debian      abd2dee0865c        2 weeks ago         1.82GB
dcso/misp-dockerized-robot          2                   2dda6dcdeafb        2 weeks ago         1.1GB
hello-world                         latest              fce289e99eb9        9 months ago        1.84kB
dcso/misp-dockerized-db             10.4.4-bionic-dev   9e56872cbc6e        292 years ago       360MB
misp@test0:~/MISP-dockerized$ docker pull -a dcso/misp-dockerized-monitoring
1-dev: Pulling from dcso/misp-dockerized-monitoring
e8dea6f7f021: Pull complete
c79ca008316d: Pull complete
d177b9207c89: Pull complete
d2fa8681413a: Pull complete
ac86e77f3fb6: Pull complete
c83226bc0dcd: Pull complete
315493d56424: Pull complete
987a2d2a43e9: Pull complete
5b2616eae40d: Pull complete
4bc7528b126a: Pull complete
775e27990c10: Pull complete
25cce0c7a51a: Pull complete
cd09f6adaea3: Pull complete
6bd0903602c6: Pull complete
868b47a8283b: Pull complete
ec4ff11f667a: Pull complete
b99736a77ee8: Pull complete
4bc198124cc9: Pull complete
Digest: sha256:21571adc81d95771c164e4096896fe5791b80ea2eef2c97db7d4cc449b95f267
hub_automatic_untested: Pulling from dcso/misp-dockerized-monitoring
f789bc42e5ba: Pull complete
6366a625bd7d: Pull complete
f8ba6779acf1: Pull complete
d714442011e8: Pull complete
717bcfd34917: Pull complete
40bc0b1f9586: Pull complete
482f5e88f671: Pull complete
d1aa8a014905: Pull complete
Digest: sha256:916f14de407006f54f040339d30f7e16927afb55465e6b63d1830b4828a3ff56
latest-dev: Pulling from dcso/misp-dockerized-monitoring
Digest: sha256:21571adc81d95771c164e4096896fe5791b80ea2eef2c97db7d4cc449b95f267
v1.15.0-dev: Pulling from dcso/misp-dockerized-monitoring
f789bc42e5ba: Already exists
6366a625bd7d: Already exists
f8ba6779acf1: Already exists
d714442011e8: Already exists
717bcfd34917: Already exists
40bc0b1f9586: Already exists
482f5e88f671: Already exists
d1aa8a014905: Already exists
51f1cb211382: Pull complete
ac2bd319fee7: Pull complete
775e27990c10: Pull complete
ee4a897b8642: Pull complete
43371bdb6571: Pull complete
705a96bfaa0b: Pull complete
84439ff69ae7: Pull complete
cc21ba1b9c9f: Pull complete
0826e50eab44: Pull complete
4bc198124cc9: Pull complete
Digest: sha256:1341cd5423835c772137950d1059d40b88159ae9fa793957cd9f0f71aceae3ba
v1.16.0-dev: Pulling from dcso/misp-dockerized-monitoring
Digest: sha256:21571adc81d95771c164e4096896fe5791b80ea2eef2c97db7d4cc449b95f267
Status: Downloaded newer image for dcso/misp-dockerized-monitoring
docker.io/dcso/misp-dockerized-monitoring
misp@test0:~/MISP-dockerized$ docker images
REPOSITORY                          TAG                      IMAGE ID            CREATED             SIZE
dcso/misp-dockerized-misp-modules   latest                   fa75db9326a9        12 days ago         1.69GB
dcso/misp-dockerized-monitoring     v1.15.0-dev              b6e63f2eeb66        12 days ago         272MB
dcso/misp-dockerized-monitoring     1-dev                    996cf9883f83        12 days ago         334MB
dcso/misp-dockerized-monitoring     latest-dev               996cf9883f83        12 days ago         334MB
dcso/misp-dockerized-monitoring     v1.16.0-dev              996cf9883f83        12 days ago         334MB
dcso/misp-dockerized-redis          5-alpine3.9              6f3559d51970        12 days ago         50.9MB
dcso/misp-dockerized-proxy          2                        caddd61a4115        2 weeks ago         24.3MB
dcso/misp-dockerized-server         2.4.113-debian           abd2dee0865c        2 weeks ago         1.82GB
dcso/misp-dockerized-robot          2                        2dda6dcdeafb        2 weeks ago         1.1GB
dcso/misp-dockerized-monitoring     hub_automatic_untested   211e8f0bd56f        3 months ago        272MB
hello-world                         latest                   fce289e99eb9        9 months ago        1.84kB
dcso/misp-dockerized-db             10.4.4-bionic-dev        9e56872cbc6e        292 years ago       360MB
misp@test0:~/MISP-dockerized$

**Comment by begunrom** [comment]
> REPOSITORY                          TAG                      IMAGE ID            CREATED             SIZE
dcso/misp-dockerized-misp-modules   latest                   fa75db9326a9        12 days ago         1.69GB
dcso/misp-dockerized-monitoring     v1.15.0-dev              b6e63f2eeb66        12 days ago         272MB
dcso/misp-dockerized-monitoring     1-dev                    996cf9883f83        12 days ago         334MB
dcso/misp-dockerized-monitoring     latest-dev               996cf9883f83        12 days ago         334MB
dcso/misp-dockerized-monitoring     v1.16.0-dev              996cf9883f83        12 days ago         334MB
dcso/misp-dockerized-redis          5-alpine3.9              6f3559d51970        12 days ago         50.9MB
dcso/misp-dockerized-proxy          2                        caddd61a4115        2 weeks ago         24.3MB
dcso/misp-dockerized-server         2.4.113-debian           abd2dee0865c        2 weeks ago         1.82GB
dcso/misp-dockerized-robot          2                        2dda6dcdeafb        2 weeks ago         1.1GB
dcso/misp-dockerized-monitoring     hub_automatic_untested   211e8f0bd56f        3 months ago        272MB
hello-world                         latest                   fce289e99eb9        9 months ago        1.84kB
dcso/misp-dockerized-db             10.4.4-bionic-dev        9e56872cbc6e        292 years ago       360MB

**Comment by begunrom** [comment]
If I specified the tag, i could download the latest-dev version (docker pull  dcso/misp-dockerized-db:latest-dev) .

Rerunning make install, did still give the 2 errors, so pulling it did not make any difference

**Comment by begunrom** [comment]
It looks like the problem is that deploy is looking for dcso/misp-dockerized-monitoring with tag latest. This one I cannot find on https://hub.docker.com/r/dcso/misp-dockerized-monitoring/tags

> $ make deploy
 ###########    Deploy Environment      ###########
The HTTP_PROXY variable is not set. Defaulting to a blank string.
The HTTPS_PROXY variable is not set. Defaulting to a blank string.
The NO_PROXY variable is not set. Defaulting to a blank string.
Pulling misp-monitoring (dcso/misp-dockerized-monitoring:latest)...
manifest for dcso/misp-dockerized-monitoring:latest not found: manifest unknown: manifest unknown
Error: No such container:path: misp-proxy:/etc/nginx
Makefile:49: recipe for target 'deploy' failed
make: *** [deploy] Error 1

**Comment by 8ear** [comment]
You can Do now different things.
First way: export DEV=true
Second way edit docker-compose.override.yml an rewrite the Tag as you require for monitoring

**Comment by begunrom** [comment]
I was intending to use this installation for production use. Is 1.2.0 a version intended to use in production or is this 1.1.1?

If I overwrite the tag what will give me production stability?

**Comment by 8ear** [comment]
Normally both Versions are intended for production. But in 1.2.0 is an Bug and I have no rights and time anymore to fix it.
I will try to integrate my Code to the official misp repository and then i can fix it.
But at the moment only @Mezzonian has rights to fix any.
But I think that currently no time for an DCSO employee is given. 😉

**Comment by begunrom** [comment]
For me it is impossible to know what is the safest choice:
dcso/misp-dockerized-monitoring tag latest-dev or v1.16.0-dev or ???
dcso/misp-dockerized-db tag latest-dev or 10.4.5-bionic-dev

**Comment by 8ear** [comment]
Latest-dev is the best choice for monitoring and db.

**Comment by begunrom** [comment]
8ear thanks, I got it going now.

**Comment by 8ear** [comment]
Great. Sorry for this.
But I'm not more working at DCSO. So I can't update the repositories anymore.

**Comment by begunrom** [comment]
I am sorry to hear that this initiative will probably die, because it is for DCSO no priority any more to maintain it. I wish you good luck to with your efforts to integrate it into the official misp repository.

**Comment by 8ear** [comment]
Thx.

**Comment by 8ear** [comment]
@begunrom Please close the issue if it is ready for you.
